# Site wide configuration

title: Dark Hypernova
tagline: 'Science and Fiction'
subtitle: "More Science, More Fiction"
description: "Science and Fiction"
description-side-bar: "It's Science!"
logo: logo-120x120.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
#url: http://openmetric.org
#baseurl: /


# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-feed

# Jekyll Collections

collections:
  til:
    output: true
  totd:
    output: true
  reading:
    output: true
  resume:
    output: true



# Custom vars
version:             0.3.1


# Gems
plugins: ['jekyll/scholar']


# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/ed/bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


# About/contact
author:
  name:              Lei Ma
  url:               https://twitter.com/emptymalei
  email:             emptymalei@qq.com


# New Settings

cover_image: front-cover.jpg # Set background image



# Site owner
owner:
  name: "OctoMiao"
  email: octomiao@interimm.org
  twitter: emptymalei
  google:
    ad-client:
    ad-slot:
  bio: "Physics is the game."
  avatar: octomiao.png # 160x160 px image for author byline
  weibo: emptymalei
  weibo-display: 章鱼喵-十只手
  github: emptymalei
  linkedin: emptymalei
  wechat: emptymalei
  cv: true
disqus-shortname: darkhypernova
swiftype: kGzvV1L-RzYo_pfREF9P # swiftype code, only the code part in your swiftype js
gacode: UA-49034078-1 # Google Analytics Code
site-source: https://github.com/emptymalei/emptymalei.github.io


# include some folders to be generated
include: ["numerical/"]

exclude: ['assets/slides/neutron-star-model/notes/', 'assets/slides/neutron-star-model/plugin/',
'assets/slides/neutron-star-model/css/theme/README.md',
'assets/slides/whygit/css/theme/README.md', 'assets/slides/whygit/plugin/','assets/webcomponents/README.md']
