menu:
  Home: /archive/
  Archives: /archive/archives/

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: emptymalei
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics: UA-49034078-1
rss:

# Disqus
disqus_shortname: hypernova

# comment_provider: facebook
# Facebook comment
# facebook:
#   appid: 123456789012345
#   comment_count: 5
#   comment_width: 840
#   comment_colorscheme: light
